apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bungeecord-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autocraft.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: bungeecord
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25577
      nodePort: {{ default 25565 .Values.proxy.port }}

---

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-knockknock-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: bungeecord
    {{- include "autocraft.labels" . | nindent 4 }}
spec:
  serviceAccountName: autocraft-bungee
  restartPolicy: OnFailure
  initContainers:
  - name: knockknock-downloader
    image: busybox
    command: ['wget', 'https://github.com/themooer1/KnockKnock/releases/download/0.1.0/KnockKnock-1.0-SNAPSHOT-jar-with-dependencies.jar', '-O', '/plugins/knockknock.jar']
    volumeMounts:
        - name: plugins
          mountPath: /plugins
  containers:
  - name: bungeecord
    image: themooer1/bungeecord
    ports:
    - containerPort: 25577
    - containerPort: 5005
    env:
    - name: TYPE
      value: "Waterfall"
      #   - name: PLUGINS
      #value: "https://github.com/themooer1/KnockKnock/releases/download/0.1.0/KnockKnock-1.0-SNAPSHOT-jar-with-dependencies.jar"

    - name: EULA
      value: {{ quote .Values.minecraft.eula }}
    volumeMounts:
        - name: plugins
          mountPath: /server/plugins
        - name: minecraft-pod-template
          mountPath: /server/minecraftPodTemplate.yaml
          subPath: minecraftPod.yaml
  volumes:
      - name: plugins
        emptyDir: {}
      - name: minecraft-pod-template
        configMap:
          name: minecraft-pod-template

  # These containers are run during pod initialization

