apiVersion: v1
kind: ConfigMap
metadata:
    name: minecraft-pod-template
    namespace: {{ .Release.Namespace }}
data:
    minecraftPod.yaml: |-
        apiVersion: v1
        kind: Pod
        metadata:
            name: minecraft-autocraft
            namespace: {{ .Release.Namespace }}
            labels:
                app: minecraft
        spec:
            restartPolicy: Never
            nodeSelector:
            {{ toYaml .Values.minecraft.nodeSelector | indent 4 }}
            tolerations:
            - key: autocraft-backend
              operator: Equal
              value: "true"
              effect: NoSchedule
            containers:
                - name: minecraft
                  image: themooer1/minecraft-server
                  ports:
                    - containerPort: 25565
                  env:
                    - name: BROADCAST_CONSOLE_TO_OPS
                      value: "TRUE"
                    - name: BROADCAST_RCON_TO_OPS
                      value: "TRUE"
                    - name: PLAYER_IDLE_TIMEOUT
                      value: "60"
                    - name: ONLINE_MODE
                      value: "FALSE"
                    - name: ENABLE_AUTOPAUSE
                      value: "TRUE"
                    - name: AUTOPAUSE_TIMEOUT_INIT
                      value: "300"
                    - name: AUTOPAUSE_TIMEOUT_EST
                      value: "300"
                    {{- range .Values.minecraft.env }}
                    - name: {{ .name }}
                      value: {{ quote .value }}
                    {{- end }}
                  volumeMounts:
                    - name: minecraft-storage
                      mountPath: /data

            volumes:
              - name: minecraft-storage
                persistentVolumeClaim:
                    claimName: {{ include "autocraft.minecraftStoragePVC" . }}