apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autocraft.minecraftStoragePVC" . }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ quote ( index .Values "nfs-server-provisioner" ).storageClass.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.minecraft.storage.size }}